FROM python:3.11-slim

WORKDIR /app

# Desabilita emissão de bytecode e bufferização de logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Instalando dependências
COPY pip-install-deps.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r pip-install-deps.txt

# Nota: Não copiamos ao código aqui porque vamos montar a  
# pasta local usando volumes do Docker para usar o hot-reloading.

EXPOSE 8000

# Executa o Uvicorn com a flag "--reload"
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]